# Generated by Django 3.1.1 on 2020-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200924_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Github_url',
            new_name='github_url',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, help_text='Enter Complete Address', max_length=100, null=True),
        ),
    ]
